/* Манифест файлов недели 06: какие блоки ядра грузить страницам.

   document.write со <script> работает синхронно во время парсинга и
   не требует ни сборки, ни fetch — единственный способ держать список
   блоков в одном месте при работе с file://. Страница обязана задать
   window.PLATFORM_BASE (путь до корня платформы) до подключения. */

(function () {
  'use strict';
  var base = window.PLATFORM_BASE || '';
  [
    'content/core/tverdoe-telo/ot-tochki-k-telu.md.js',
    'content/core/tverdoe-telo/ris-gantel-poperek.md.js',
    'content/core/tverdoe-telo/uravnenie-momentov-os.md.js',
    'content/core/tverdoe-telo/ris-razlozhenie-k-osi.md.js',
    'content/core/tverdoe-telo/primer-gantel.md.js',
    'content/core/tverdoe-telo/ris-gantel.md.js',
    'content/core/tverdoe-telo/model-tverdogo-tela.md.js',
    'content/core/tverdoe-telo/ris-dve-tochki-tela.md.js',
    'content/core/tverdoe-telo/vrashchenie-vokrug-osi.md.js',
    'content/core/tverdoe-telo/ris-skamya.md.js',
    'content/core/tverdoe-telo/moment-inercii-sterzhnya.md.js',
    'content/core/tverdoe-telo/ris-sterzhen-dx.md.js',
    'content/core/tverdoe-telo/moment-inercii-tochki.md.js',
    'content/core/tverdoe-telo/ris-perpendikulyarnye-osi.md.js',
    'content/core/tverdoe-telo/shar-i-disk.md.js',
    'content/core/tverdoe-telo/ris-disk-kolca.md.js',
    'content/core/tverdoe-telo/ris-shar-sloi.md.js',
    'content/core/tverdoe-telo/teorema-gyujgensa-shtejnera.md.js',
    'content/core/tverdoe-telo/ris-shtejner.md.js',
    'content/core/tverdoe-telo/tenzor-inercii.md.js',
    'content/core/tverdoe-telo/ellipsoid-inercii.md.js',
    'content/core/tverdoe-telo/ris-ellipsoid-inercii.md.js',
    'content/core/tverdoe-telo/ris-kub-treugolnik.md.js',
    'content/core/tverdoe-telo/tenzor-kak-kovariaciya.md.js',
    'content/core/tverdoe-telo/ris-oblako-glavnye-osi.md.js',
    'content/core/tverdoe-telo/mgnovennaya-os.md.js',
    'content/core/tverdoe-telo/ris-nulevaya-skorost.md.js',
    'content/core/tverdoe-telo/primer-koleso.md.js',
    'content/core/tverdoe-telo/ris-kachenie-yuz.md.js',
    'content/core/tverdoe-telo/ris-koleso.md.js',
    'content/core/tverdoe-telo/razlozhenie-dvizheniya.md.js',
    'content/core/tverdoe-telo/ris-dvizhushchijsya-polyus.md.js',
    'content/core/tverdoe-telo/uravnenie-momentov-ploskoe.md.js',
    'content/core/tverdoe-telo/primer-skatyvanie.md.js',
    'content/core/tverdoe-telo/ris-obruch-s-gruzom.md.js',
    'content/core/tverdoe-telo/primer-katushka.md.js',
    'content/core/tverdoe-telo/ris-katushka.md.js',
    'content/core/tverdoe-telo/teorema-ejlera.md.js',
    'content/core/tverdoe-telo/ris-povoroty-kartochki.md.js',
    'content/core/tverdoe-telo/uravneniya-ejlera.md.js',
    'content/core/tverdoe-telo/vrashchenie-bez-opor.md.js',
    'content/core/tverdoe-telo/ris-brusok-osi.md.js',
    'content/core/tverdoe-telo/giroskop.md.js',
    'content/core/tverdoe-telo/ris-sterzhen-na-sharnire.md.js',
    'content/core/tverdoe-telo/ris-volchok.md.js',
    'content/core/tverdoe-telo/itog-kakaya-os-stoit.md.js',
    'content/core/tverdoe-telo/demka-gantel-na-motore.md.js',
    'content/core/tverdoe-telo/demka-skamya.md.js',
    'content/core/tverdoe-telo/demka-gonka-cilindrov.md.js',
    'content/core/tverdoe-telo/demka-tenzor-povorot.md.js',
    'content/core/tverdoe-telo/demka-mgnovennaya-os.md.js',
    'content/core/tverdoe-telo/demka-katushka.md.js',
    'content/core/tverdoe-telo/demka-poryadok-povorotov-06.md.js',
    'content/core/tverdoe-telo/demka-svobodnoe-vrashchenie.md.js',
    'content/core/tverdoe-telo/demka-giroskop.md.js',
    'content/core/tverdoe-telo/vopros-tt-01.md.js',
    'content/core/tverdoe-telo/vopros-tt-02.md.js',
    'content/core/tverdoe-telo/vopros-tt-03.md.js',
    'content/core/tverdoe-telo/vopros-tt-04.md.js',
    'content/core/tverdoe-telo/vopros-tt-05.md.js',
    'content/core/tverdoe-telo/vopros-tt-06.md.js',
    'content/core/tverdoe-telo/vopros-tt-07.md.js',
    'content/core/tverdoe-telo/vopros-tt-08.md.js',
    'content/core/tverdoe-telo/vopros-tt-09.md.js',
    'content/core/tverdoe-telo/vopros-tt-10.md.js',
    'content/core/tverdoe-telo/vopros-tt-11.md.js',
    'content/core/tverdoe-telo/zadacha-tt-shtanga.md.js',
    'content/core/tverdoe-telo/zadacha-tt-truba.md.js',
    'content/core/tverdoe-telo/zadacha-tt-myach.md.js',
    'content/core/tverdoe-telo/zadacha-tt-meteorit.md.js',
    'content/core/tverdoe-telo/zadacha-tt-propeller.md.js',
    'content/core/tverdoe-telo/figs/gantel-poperek.svg.js',
    'content/core/tverdoe-telo/figs/razlozhenie-k-osi.svg.js',
    'content/core/tverdoe-telo/figs/gantel.svg.js',
    'content/core/tverdoe-telo/figs/dve-tochki-tela.svg.js',
    'content/core/tverdoe-telo/figs/skamya.svg.js',
    'content/core/tverdoe-telo/figs/sterzhen-dx.svg.js',
    'content/core/tverdoe-telo/figs/perpendikulyarnye-osi.svg.js',
    'content/core/tverdoe-telo/figs/disk-kolca.svg.js',
    'content/core/tverdoe-telo/figs/shar-sloi.svg.js',
    'content/core/tverdoe-telo/figs/shtejner.svg.js',
    'content/core/tverdoe-telo/figs/ellipsoid-inercii.svg.js',
    'content/core/tverdoe-telo/figs/kub-treugolnik.svg.js',
    'content/core/tverdoe-telo/figs/oblako-glavnye-osi.svg.js',
    'content/core/tverdoe-telo/figs/nulevaya-skorost.svg.js',
    'content/core/tverdoe-telo/figs/kachenie-yuz.svg.js',
    'content/core/tverdoe-telo/figs/koleso.svg.js',
    'content/core/tverdoe-telo/figs/dvizhushchijsya-polyus.svg.js',
    'content/core/tverdoe-telo/figs/obruch-s-gruzom.svg.js',
    'content/core/tverdoe-telo/figs/katushka.svg.js',
    'content/core/tverdoe-telo/figs/povoroty-kartochki.svg.js',
    'content/core/tverdoe-telo/figs/brusok-osi.svg.js',
    'content/core/tverdoe-telo/figs/sterzhen-na-sharnire.svg.js',
    'content/core/tverdoe-telo/figs/volchok.svg.js',
    /* цели межнедельных [[...]]-ссылок — чужие блоки, только чтение */
    'content/core/moment-impulsa/itog-tri-mnozhitelya.md.js',
    'content/core/moment-impulsa/moment-impulsa.md.js',
    'content/core/moment-impulsa/moment-sily.md.js',
    'content/core/kinematika/materialnaya-tochka.md.js',
    'content/core/zakony-nyutona/itog-zakony-vybirayut.md.js',
    'content/core/zakony-nyutona/uravnenie-dvizheniya.md.js',
    'content/core/zakony-nyutona/teorema-o-centre-mass.md.js',
    'content/core/moment-impulsa/moment-vnutrennih-sil.md.js',
    'content/core/zakony-nyutona/integralnaya-forma.md.js',
    'content/core/kinematika/godograf.md.js',
    'content/core/rabota-energiya/rabota-vnutrennih-sil.md.js',
    'content/core/rabota-energiya/kineticheskaya-energiya.md.js',
    'content/core/zakony-nyutona/sistema-tochek.md.js',
    'content/core/deformacii-gidrodinamika/ot-tverdogo-tela-k-sploshnoj-srede.md.js',
    'content/core/kinematika/uglovaya-skorost.md.js',
    'content/core/zakony-nyutona/vtoroj-zakon.md.js',
    'content/core/kolebaniya/fizicheskij-mayatnik.md.js',
    'content/core/moment-impulsa/sharik-na-niti.md.js',
    'content/core/kolebaniya/zadacha-kol-plastinki.md.js',
    'content/core/zakony-nyutona/centr-mass.md.js',
    'content/core/rabota-energiya/teorema-kyoniga.md.js',
    'content/core/kinematika/normalnoe-i-tangencialnoe.md.js',
    'content/core/kinematika/sistema-otscheta.md.js',
    'content/core/zakony-nyutona/zadacha-treh-tel.md.js',
    'content/core/rabota-energiya/klassifikaciya-sil.md.js'
  ].forEach(function (p) {
    document.write('<script src="' + base + p + '"><\/script>');
  });
})();
