/* Манифест файлов недели 04: какие блоки ядра грузить страницам.

   document.write со <script> работает синхронно во время парсинга и
   не требует ни сборки, ни fetch — единственный способ держать список
   блоков в одном месте при работе с file://. Страница обязана задать
   window.PLATFORM_BASE (путь до корня платформы) до подключения. */

(function () {
  'use strict';
  var base = window.PLATFORM_BASE || '';
  [
    'content/core/rabota-energiya/ot-impulsa-k-energii.md.js',
    'content/core/rabota-energiya/mehanicheskaya-rabota.md.js',
    'content/core/rabota-energiya/ris-mech-work.md.js',
    'content/core/rabota-energiya/moshchnost.md.js',
    'content/core/rabota-energiya/kineticheskaya-energiya.md.js',
    'content/core/rabota-energiya/ris-prirashchenie-skorosti.md.js',
    'content/core/rabota-energiya/rabota-vnutrennih-sil.md.js',
    'content/core/rabota-energiya/ris-rabota-pary.md.js',
    'content/core/rabota-energiya/ris-lenta-dve-sistemy.md.js',
    'content/core/rabota-energiya/teorema-kyoniga.md.js',
    'content/core/rabota-energiya/ris-kyonig-skorosti.md.js',
    'content/core/rabota-energiya/ris-mashina-doroga.md.js',
    'content/core/rabota-energiya/ris-koleso-peresadka.md.js',
    'content/core/rabota-energiya/konservativnye-sily.md.js',
    'content/core/rabota-energiya/ris-vihrevoe-pole.md.js',
    'content/core/rabota-energiya/ris-kontur-raboty.md.js',
    'content/core/rabota-energiya/potencialnaya-energiya.md.js',
    'content/core/rabota-energiya/ris-tri-tochki.md.js',
    'content/core/rabota-energiya/centralnye-sily.md.js',
    'content/core/rabota-energiya/ris-centralnoe-pole.md.js',
    'content/core/rabota-energiya/klassifikaciya-sil.md.js',
    'content/core/rabota-energiya/zakon-sohraneniya-energii.md.js',
    'content/core/rabota-energiya/sila-i-potencialnaya-energiya.md.js',
    'content/core/rabota-energiya/ris-sila-po-potencialu.md.js',
    'content/core/rabota-energiya/ris-gorka-reakciya.md.js',
    'content/core/rabota-energiya/spusk-i-trenie.md.js',
    'content/core/rabota-energiya/ris-uroven-energii.md.js',
    'content/core/rabota-energiya/tipy-stolknovenij.md.js',
    'content/core/rabota-energiya/ris-dve-chasti-udara.md.js',
    'content/core/rabota-energiya/uprugij-udar-1d.md.js',
    'content/core/rabota-energiya/ris-udar-na-pryamoj.md.js',
    'content/core/rabota-energiya/sistema-centra-mass.md.js',
    'content/core/rabota-energiya/ris-impulsy-v-scm.md.js',
    'content/core/rabota-energiya/ris-rasseyanie.md.js',
    'content/core/rabota-energiya/predelnyj-ugol.md.js',
    'content/core/rabota-energiya/ris-vektornaya-diagramma.md.js',
    'content/core/rabota-energiya/porogovaya-energiya.md.js',
    'content/core/rabota-energiya/ris-slipanie-mashin.md.js',
    'content/core/rabota-energiya/ris-gorka-porog.md.js',
    'content/core/rabota-energiya/itog-dve-velichiny.md.js',
    'content/core/rabota-energiya/demka-para-sil.md.js',
    'content/core/rabota-energiya/demka-mashinka-avtomobil.md.js',
    'content/core/rabota-energiya/demka-gruz-generator.md.js',
    'content/core/rabota-energiya/demka-gorka-potencial.md.js',
    'content/core/rabota-energiya/demka-sharik-spusk.md.js',
    'content/core/rabota-energiya/demka-pi-v-soudareniyah.md.js',
    'content/core/rabota-energiya/demka-udar-v-scm.md.js',
    'content/core/rabota-energiya/vopros-re-01.md.js',
    'content/core/rabota-energiya/vopros-re-02.md.js',
    'content/core/rabota-energiya/vopros-re-03.md.js',
    'content/core/rabota-energiya/vopros-re-04.md.js',
    'content/core/rabota-energiya/vopros-re-05.md.js',
    'content/core/rabota-energiya/vopros-re-06.md.js',
    'content/core/rabota-energiya/vopros-re-07.md.js',
    'content/core/rabota-energiya/vopros-re-08.md.js',
    'content/core/rabota-energiya/vopros-re-09.md.js',
    'content/core/rabota-energiya/vopros-re-10.md.js',
    'content/core/rabota-energiya/vopros-re-11.md.js',
    'content/core/rabota-energiya/vopros-re-12.md.js',
    'content/core/rabota-energiya/zadacha-udar-o-stenku.md.js',
    'content/core/rabota-energiya/zadacha-pruzhina.md.js',
    'content/core/rabota-energiya/zadacha-lennard-dzhons.md.js',
    'content/core/rabota-energiya/figs/mech-work.svg.js',
    'content/core/rabota-energiya/figs/kontur-raboty.svg.js',
    'content/core/rabota-energiya/figs/rasseyanie.svg.js',
    'content/core/rabota-energiya/figs/vektornaya-diagramma.svg.js',
    'content/core/rabota-energiya/figs/gorka-porog.svg.js',
    'content/core/rabota-energiya/figs/pruzhina-gruz.svg.js',
    'content/core/rabota-energiya/figs/lennard-dzhons.svg.js',
    'content/core/rabota-energiya/figs/vihrevoe-pole.svg.js',
    'content/core/rabota-energiya/figs/prirashchenie-skorosti.svg.js',
    'content/core/rabota-energiya/figs/rabota-pary.svg.js',
    'content/core/rabota-energiya/figs/kyonig-skorosti.svg.js',
    'content/core/rabota-energiya/figs/sila-po-potencialu.svg.js',
    'content/core/rabota-energiya/figs/dve-chasti-udara.svg.js',
    'content/core/rabota-energiya/figs/udar-na-pryamoj.svg.js',
    'content/core/rabota-energiya/figs/impulsy-v-scm.svg.js',
    'content/core/rabota-energiya/figs/slipanie-mashin.svg.js',
    'content/core/rabota-energiya/figs/tri-tochki.svg.js',
    'content/core/rabota-energiya/figs/koleso-peresadka.svg.js',
    'content/core/rabota-energiya/figs/centralnoe-pole.svg.js',
    'content/core/rabota-energiya/figs/gorka-reakciya.svg.js',
    'content/core/rabota-energiya/figs/uroven-energii.svg.js',
    'content/core/rabota-energiya/figs/mashina-doroga.svg.js',
    'content/core/rabota-energiya/figs/lenta-dve-sistemy.svg.js',
    /* цели межнедельных [[...]]-ссылок — чужие блоки, только чтение */
    'content/core/zakony-nyutona/vtoroj-zakon.md.js',
    'content/core/zakony-nyutona/tretij-zakon.md.js',
    'content/core/zakony-nyutona/sistema-tochek.md.js',
    'content/core/zakony-nyutona/princip-otnositelnosti.md.js',
    'content/core/zakony-nyutona/integralnaya-forma.md.js',
    'content/core/zakony-nyutona/zadacha-dvuh-tel.md.js',
    'content/core/zakony-nyutona/centr-mass.md.js',
    'content/core/zakony-nyutona/teorema-o-centre-mass.md.js',
    'content/core/zakony-nyutona/itog-zakony-vybirayut.md.js',
    /* рисунок третьей недели на слайде 13 колоды (замечание автора 21.09
       к слайду 12): без него офлайн-колода теряла кадр пересадки */
    'content/core/zakony-nyutona/ris-dve-sistemy.md.js',
    'content/core/zakony-nyutona/figs/dve-sistemy.svg.js'
  ].forEach(function (p) {
    document.write('<script src="' + base + p + '"><\/script>');
  });
})();
