/* Манифест файлов недели 02: какие блоки ядра грузить страницам.

   document.write со <script> работает синхронно во время парсинга и
   не требует ни сборки, ни fetch — единственный способ держать список
   блоков в одном месте при работе с file://. Страница обязана задать
   window.PLATFORM_BASE (путь до корня платформы) до подключения. */

(function () {
  'use strict';
  var base = window.PLATFORM_BASE || '';
  [
    'content/core/kinematika/pochemu-mekhanika.md.js',
    'content/core/kinematika/aksiomy-i-formalizaciya.md.js',
    'content/core/kinematika/chto-takoe-kinematika.md.js',
    'content/core/kinematika/prostranstvo-i-vremya.md.js',
    'content/core/kinematika/parallaks-i-zatmenie.md.js',
    'content/core/kinematika/otnositelnost-dvizheniya.md.js',
    'content/core/kinematika/sistema-otscheta.md.js',
    'content/core/kinematika/materialnaya-tochka.md.js',
    'content/core/kinematika/radius-vektor.md.js',
    'content/core/kinematika/ris-radius-vektor.md.js',
    'content/core/kinematika/traektoriya.md.js',
    'content/core/kinematika/peremeshchenie.md.js',
    'content/core/kinematika/ris-peremeshchenie.md.js',
    'content/core/kinematika/skorost.md.js',
    'content/core/kinematika/integrirovanie-skorosti.md.js',
    'content/core/kinematika/put.md.js',
    'content/core/kinematika/uskorenie.md.js',
    'content/core/kinematika/ravnouskorennoe-dvizhenie.md.js',
    'content/core/kinematika/godograf.md.js',
    'content/core/kinematika/uglovaya-skorost.md.js',
    'content/core/kinematika/ris-uglovaya-skorost.md.js',
    'content/core/kinematika/normalnoe-i-tangencialnoe.md.js',
    'content/core/kinematika/ris-krivizna.md.js',
    'content/core/kinematika/radius-krivizny.md.js',
    'content/core/kinematika/itog-chetyre-vozvrata.md.js',
    'content/core/kinematika/vopros-kin-01.md.js',
    'content/core/kinematika/vopros-kin-02.md.js',
    'content/core/kinematika/vopros-kin-03.md.js',
    'content/core/kinematika/vopros-kin-04.md.js',
    'content/core/kinematika/vopros-kin-05.md.js',
    'content/core/kinematika/vopros-kin-06.md.js',
    'content/core/kinematika/vopros-kin-07.md.js',
    'content/core/kinematika/vopros-kin-08.md.js',
    'content/core/kinematika/vopros-kin-09.md.js',
    'content/core/kinematika/zadacha-grafiki.md.js',
    'content/core/kinematika/zadacha-myach.md.js',
    'content/core/kinematika/zadacha-okruzhnost.md.js',
    'content/core/kinematika/zadacha-eksponenta.md.js',
    /* обёртки рисунков, вставших в колоду 07.09: колода ищет блок по id,
       а адрес картинки берёт из его поля fig */
    'content/core/kinematika/ris-brosok-pod-uglom.md.js',
    'content/core/kinematika/ris-cepochka-a-v-x.md.js',
    'content/core/kinematika/ris-godograf.md.js',
    'content/core/kinematika/ris-horda-sekushchaya.md.js',
    'content/core/kinematika/ris-izlom-i-peregib.md.js',
    'content/core/kinematika/ris-kasatelnaya-kontrprimer.md.js',
    'content/core/kinematika/ris-kirpich-povoroty.md.js',
    'content/core/kinematika/ris-lestnica-chetyre.md.js',
    'content/core/kinematika/ris-parabola-krivizna.md.js',
    'content/core/kinematika/ris-parallaks.md.js',
    'content/core/kinematika/ris-samolet-dva-voprosa.md.js',
    'content/core/kinematika/ris-sfericheskij-treugolnik.md.js',
    'content/core/kinematika/ris-soprovozhdayushchij-bazis.md.js',
    'content/core/kinematika/ris-stolbiki-znak.md.js',
    'content/core/kinematika/ris-tochka-v-dvuh-osyah.md.js',
    'content/core/kinematika/ris-traektoriya-izlom-razryv.md.js',
    'content/core/kinematika/ris-treugolnik-tau.md.js',
    'content/core/kinematika/ris-ugol-bez-skachka.md.js',
    'content/core/kinematika/ris-vintovaya-liniya.md.js',
    'content/core/kinematika/ris-zatmenie-1919.md.js',
    'content/core/kinematika/figs/radius-vektor.svg.js',
    'content/core/kinematika/figs/peremeshchenie.svg.js',
    'content/core/kinematika/figs/uglovaya-skorost.svg.js',
    'content/core/kinematika/figs/krivizna.svg.js',
    'content/core/kinematika/figs/zadacha-grafik-v.svg.js',
    'content/core/kinematika/figs/zadacha-grafik-s.svg.js',
    'content/core/kinematika/figs/zadacha-grafik-a.svg.js',
    /* сами рисунки этих обёрток */
    'content/core/kinematika/figs/brosok-pod-uglom.svg.js',
    'content/core/kinematika/figs/cepochka-a-v-x.svg.js',
    'content/core/kinematika/figs/godograf.svg.js',
    'content/core/kinematika/figs/horda-sekushchaya.svg.js',
    'content/core/kinematika/figs/izlom-i-peregib.svg.js',
    'content/core/kinematika/figs/kasatelnaya-kontrprimer.svg.js',
    'content/core/kinematika/figs/kirpich-povoroty.svg.js',
    'content/core/kinematika/figs/lestnica-chetyre.svg.js',
    'content/core/kinematika/figs/parabola-krivizna.svg.js',
    'content/core/kinematika/figs/parallaks.svg.js',
    'content/core/kinematika/figs/samolet-dva-voprosa.svg.js',
    'content/core/kinematika/figs/sfericheskij-treugolnik.svg.js',
    'content/core/kinematika/figs/soprovozhdayushchij-bazis.svg.js',
    'content/core/kinematika/figs/stolbiki-znak.svg.js',
    'content/core/kinematika/figs/tochka-v-dvuh-osyah.svg.js',
    'content/core/kinematika/figs/traektoriya-izlom-razryv.svg.js',
    'content/core/kinematika/figs/treugolnik-tau.svg.js',
    'content/core/kinematika/figs/ugol-bez-skachka.svg.js',
    'content/core/kinematika/figs/vintovaya-liniya.svg.js',
    'content/core/kinematika/figs/zatmenie-1919.svg.js',
    /* блоки-демки: из них колода берёт адрес файла демки (deck-blocks.js),
       а страница недели — описание. Заведены 07.09 */
    'content/core/kinematika/demka-parallaks-v-trubu.md.js',
    'content/core/kinematika/demka-parallaks-krivizna.md.js',
    'content/core/kinematika/demka-massa-krivit-prostranstvo.md.js',
    'content/core/kinematika/demka-otnositelnost-dvizheniya.md.js',
    'content/core/kinematika/demka-povorot-osej.md.js',
    'content/core/kinematika/demka-obod-kolesa.md.js',
    'content/core/kinematika/demka-kasatelnaya.md.js',
    'content/core/kinematika/demka-kadrovyj-integral.md.js',
    'content/core/kinematika/demka-drozhanie-s-drejfom.md.js',
    'content/core/kinematika/demka-godograf.md.js',
    'content/core/kinematika/demka-uskorenie-v-povorote.md.js',
    'content/core/kinematika/demka-poryadok-povorotov.md.js',
    'content/core/kinematika/demka-krivizna-okruzhnost.md.js',
    /* цели межнедельных [[...]]-ссылок — чужие блоки, только чтение */
    'content/core/razmernosti/gradusy-i-radiany.md.js',
    'content/core/razmernosti/formula-razmernosti.md.js',
    'content/core/predmet-fiziki/chto-takoe-fizika.md.js',
    'content/core/zakony-nyutona/pervyj-zakon.md.js',
    'content/core/zakony-nyutona/princip-otnositelnosti.md.js',
    'content/core/moment-impulsa/sektorialnaya-skorost.md.js',
    'content/core/vtoroe-nachalo/neobratimost-i-entropiya.md.js'
  ].forEach(function (p) {
    document.write('<script src="' + base + p + '"><\/script>');
  });
})();
