/* Манифест файлов недели 05: какие блоки ядра грузить страницам.

   document.write со <script> работает синхронно во время парсинга и
   не требует ни сборки, ни fetch — единственный способ держать список
   блоков в одном месте при работе с file://. Страница обязана задать
   window.PLATFORM_BASE (путь до корня платформы) до подключения. */

(function () {
  'use strict';
  var base = window.PLATFORM_BASE || '';
  [
    'content/core/moment-impulsa/ot-energii-k-momentu.md.js',
    'content/core/moment-impulsa/moment-impulsa.md.js',
    'content/core/moment-impulsa/ris-moment-impulsa.md.js',
    'content/core/moment-impulsa/ris-pravilo-pravoj-ruki.md.js',
    'content/core/moment-impulsa/moment-sily.md.js',
    'content/core/moment-impulsa/ris-plecho-sily.md.js',
    'content/core/moment-impulsa/moment-vnutrennih-sil.md.js',
    'content/core/moment-impulsa/ris-vnutrennie-momenty.md.js',
    'content/core/moment-impulsa/ris-tri-mnozhitelya.md.js',
    'content/core/moment-impulsa/sharik-na-niti.md.js',
    'content/core/moment-impulsa/ris-sharik-na-niti.md.js',
    'content/core/moment-impulsa/demka-sharik-na-niti.md.js',
    'content/core/moment-impulsa/demka-gravitacionnye-volny.md.js',
    'content/core/moment-impulsa/demka-ravnye-ploshchadi.md.js',
    'content/core/moment-impulsa/demka-effektivnaya-energiya.md.js',
    'content/core/moment-impulsa/demka-obratnyj-kvadrat.md.js',
    'content/core/moment-impulsa/demka-dva-tela.md.js',
    'content/core/moment-impulsa/demka-pushka-nyutona.md.js',
    'content/core/moment-impulsa/demka-gravitacionnyj-manevr.md.js',
    'content/core/moment-impulsa/demka-razvorot-mahovikom.md.js',
    'content/core/moment-impulsa/demka-shahta-cherez-planetu.md.js',
    'content/core/moment-impulsa/demka-mars-s-zemli.md.js',
    'content/core/moment-impulsa/demka-orbita-marsa-po-tablice.md.js',
    'content/core/moment-impulsa/sektorialnaya-skorost.md.js',
    'content/core/moment-impulsa/ris-sektorialnaya-skorost.md.js',
    'content/core/moment-impulsa/ris-planeta-impuls.md.js',
    'content/core/moment-impulsa/ris-tolchki-ploshchadi.md.js',
    'content/core/moment-impulsa/nebo-i-tablicy.md.js',
    'content/core/moment-impulsa/zakony-keplera.md.js',
    'content/core/moment-impulsa/ris-ellips.md.js',
    'content/core/moment-impulsa/zakon-tyagoteniya.md.js',
    'content/core/moment-impulsa/ris-cavendish.md.js',
    'content/core/moment-impulsa/dannye-dayut-zakony.md.js',
    'content/core/moment-impulsa/gravitacionnoe-pole.md.js',
    'content/core/moment-impulsa/ris-vektornyj-zakon.md.js',
    'content/core/moment-impulsa/potencialnaya-energiya-tyagoteniya.md.js',
    'content/core/moment-impulsa/dva-tela-na-orbite.md.js',
    'content/core/moment-impulsa/zakony-sohraneniya-orbity.md.js',
    'content/core/moment-impulsa/ris-polyarnye-komponenty.md.js',
    'content/core/moment-impulsa/effektivnyj-potencial.md.js',
    'content/core/moment-impulsa/ris-effektivnyj-potencial.md.js',
    'content/core/moment-impulsa/kosmicheskie-skorosti.md.js',
    'content/core/moment-impulsa/parametry-orbity.md.js',
    'content/core/moment-impulsa/ris-ellips-orbita.md.js',
    'content/core/moment-impulsa/tretij-zakon-keplera.md.js',
    'content/core/moment-impulsa/chto-daet-obratnyj-kvadrat.md.js',
    'content/core/moment-impulsa/ris-ellips-rozetka.md.js',
    'content/core/moment-impulsa/itog-tri-mnozhitelya.md.js',
    'content/core/moment-impulsa/vopros-mi-01.md.js',
    'content/core/moment-impulsa/vopros-mi-02.md.js',
    'content/core/moment-impulsa/vopros-mi-03.md.js',
    'content/core/moment-impulsa/vopros-mi-04.md.js',
    'content/core/moment-impulsa/vopros-mi-05.md.js',
    'content/core/moment-impulsa/vopros-mi-06.md.js',
    'content/core/moment-impulsa/vopros-mi-07.md.js',
    'content/core/moment-impulsa/vopros-mi-08.md.js',
    'content/core/moment-impulsa/vopros-mi-09.md.js',
    'content/core/moment-impulsa/vopros-mi-10.md.js',
    'content/core/moment-impulsa/zadacha-geostacionar.md.js',
    'content/core/moment-impulsa/zadacha-dvojnaya-zvezda.md.js',
    'content/core/moment-impulsa/zadacha-uhod-s-orbity.md.js',
    'content/core/moment-impulsa/figs/moment-l-def.svg.js',
    'content/core/moment-impulsa/figs/pravilo-pravoj-ruki.svg.js',
    'content/core/moment-impulsa/figs/vnutrennie-momenty.svg.js',
    'content/core/moment-impulsa/figs/sektorialnaya-skorost.svg.js',
    'content/core/moment-impulsa/figs/ellips-fokusy.svg.js',
    'content/core/moment-impulsa/figs/ellips-orbita.svg.js',
    'content/core/moment-impulsa/figs/effektivnyj-potencial.svg.js',
    'content/core/moment-impulsa/figs/geostacionar.svg.js',
    'content/core/moment-impulsa/figs/dvojnaya-zvezda.svg.js',
    'content/core/moment-impulsa/figs/plecho-sily.svg.js',
    'content/core/moment-impulsa/figs/sharik-na-niti.svg.js',
    'content/core/moment-impulsa/figs/vektornyj-zakon.svg.js',
    'content/core/moment-impulsa/figs/polyarnye-komponenty.svg.js',
    'content/core/moment-impulsa/figs/tri-mnozhitelya.svg.js',
    'content/core/moment-impulsa/figs/planeta-impuls.svg.js',
    'content/core/moment-impulsa/figs/tolchki-ploshchadi.svg.js',
    'content/core/moment-impulsa/figs/ellips-rozetka.svg.js',
    /* цели межнедельных [[...]]-ссылок — чужие блоки, только чтение */
    'content/core/kinematika/sistema-otscheta.md.js',
    'content/core/kinematika/uglovaya-skorost.md.js',
    'content/core/zakony-nyutona/vtoroj-zakon.md.js',
    'content/core/zakony-nyutona/tretij-zakon.md.js',
    'content/core/zakony-nyutona/sistema-tochek.md.js',
    'content/core/zakony-nyutona/zadacha-dvuh-tel.md.js',
    'content/core/zakony-nyutona/massa-i-impuls.md.js',
    'content/core/zakony-nyutona/princip-superpozicii.md.js',
    'content/core/zakony-nyutona/granicy-primenimosti.md.js',
    'content/core/zakony-nyutona/chislennoe-integrirovanie.md.js',
    'content/core/zakony-nyutona/centr-mass.md.js',
    'content/core/rabota-energiya/kineticheskaya-energiya.md.js',
    'content/core/rabota-energiya/rabota-vnutrennih-sil.md.js',
    'content/core/rabota-energiya/potencialnaya-energiya.md.js',
    'content/core/rabota-energiya/centralnye-sily.md.js',
    'content/core/rabota-energiya/zakon-sohraneniya-energii.md.js',
    'content/core/rabota-energiya/sila-i-potencialnaya-energiya.md.js',
    'content/core/rabota-energiya/spusk-i-trenie.md.js',
    'content/core/rabota-energiya/itog-dve-velichiny.md.js',
    'content/core/tverdoe-telo/uravnenie-momentov-ploskoe.md.js'
  ].forEach(function (p) {
    document.write('<script src="' + base + p + '"><\/script>');
  });
})();
